# Generated by Django 3.1.3 on 2020-11-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='incomeexpense',
            options={'ordering': ['-date'], 'verbose_name': 'income/expense', 'verbose_name_plural': 'incomes/expenses'},
        ),
        migrations.AddField(
            model_name='incomeexpense',
            name='type',
            field=models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
