# Generated by Django 4.0.2 on 2022-02-06 10:14

from django.db import migrations, models
from enum import Enum


class IncomeExpenseChoices(Enum):
    I = "Income"
    E = "Expense"


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_auto_20201130_1951"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="incomeexpense",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="incomeexpense",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="incomeexpense",
            name="type",
            field=models.CharField(
                choices=[(IncomeExpenseChoices["I"], "Income"), (IncomeExpenseChoices["E"], "Expense")], max_length=1
            ),
        ),
    ]
