# Generated by Django 4.0.2 on 2022-02-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_category_color_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeexpense',
            name='type',
            field=models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], max_length=1),
        ),
    ]
